fomio_app_url:
  type: string
  default: ""
fomio_owned_me_notifications_enabled:
  type: bool
  default: false
fomio_owned_me_activity_enabled:
  type: bool
  default: true
fomio_owned_me_invites_enabled:
  type: bool
  default: false
fomio_owned_me_preferences_shell_enabled:
  type: bool
  default: false
